/**
 * A consumer genome raw file into the twelve rows of `GENOME_CATALOG`, and
 * nothing else.
 *
 * 23andMe writes `rsid chromosome position genotype`, AncestryDNA writes
 * `rsid chromosome position allele1 allele2`, both tab separated, both with
 * `#` comment blocks and a header line. The file has ~600k rows and we want
 * twenty of them, so the parser walks the text one line at a time and keeps
 * only what the catalog asks for. Nothing outside the catalog is ever stored
 * or shown.
 *
 * `parseGenome`, `callGenome` and `genomeFacts` are pure; `saveGenome` is the
 * one function that writes.
 */
import { eq } from "drizzle-orm";
import { getDb, genomeVariants } from "@/db";
import { writeFact } from "./facts";
import {
  CATALOG_RSIDS,
  GENOME_CATALOG,
  normalizeGenotype,
  type GenomeCall,
  type GenomeRow,
} from "./genome-catalog";

export interface ParsedVariant {
  rsid: string;
  chromosome: string | null;
  position: number | null;
  genotype: string;
}

/**
 * The first lines of a `.txt` upload, as the spec's sniff test wants them:
 * a 23andMe comment block, a bare 23andMe header, or the AncestryDNA header.
 */
export function looksLikeGenome(head: string): boolean {
  const text = head.slice(0, 4000);
  if (/^#\s*rsid/m.test(text)) return true;
  if (/^rsid\s+chromosome\s+position\s+genotype/im.test(text)) return true;
  if (/^rsid\s+chromosome\s+position\s+allele1\s+allele2/im.test(text))
    return true;
  return /^#\s*(This data file generated by (23andMe|AncestryDNA))/im.test(
    text,
  );
}

/** The catalog rsids this file carries. Everything else is dropped as it is read. */
export function parseGenome(text: string): ParsedVariant[] {
  const out: ParsedVariant[] = [];
  let at = 0;
  while (at < text.length) {
    let end = text.indexOf("\n", at);
    if (end === -1) end = text.length;
    const line = text.slice(at, end).trim();
    at = end + 1;
    if (!line || line.startsWith("#")) continue;
    // ponytail: a lookup before a split. 600k rows, twenty of them matter.
    if (!line.startsWith("rs")) continue;
    const cols = line.split(/\t| +/);
    const rsid = cols[0]!.toLowerCase();
    if (!CATALOG_RSIDS.has(rsid)) continue;
    const raw = cols.length >= 5 ? `${cols[3]}${cols[4]}` : (cols[3] ?? "");
    const genotype = normalizeGenotype(raw);
    if (!genotype) continue;
    const position = Number(cols[2]);
    out.push({
      rsid,
      chromosome: cols[1] ?? null,
      position: Number.isFinite(position) ? position : null,
      genotype,
    });
  }
  return out;
}

export interface GenomeResult {
  row: GenomeRow;
  /** null when this array does not carry the rsids the row needs. */
  result: GenomeCall | null;
  /** The rsids the row wanted and the file did not have. */
  absent: string[];
}

/** Every catalog row against one person's variants, in catalog order. */
export function callGenome(variants: ParsedVariant[]): GenomeResult[] {
  const byRsid: Record<string, string> = {};
  for (const v of variants) byRsid[v.rsid] = v.genotype;
  return GENOME_CATALOG.map((row) => ({
    row,
    result: row.call(byRsid),
    absent: row.rsids.filter((r) => !byRsid[r]),
  }));
}

/** The profile facts a set of calls writes: `{ "genome:apoe": "e3/e4", ... }`. */
export function genomeFacts(results: GenomeResult[]): Record<string, string> {
  const out: Record<string, string> = {};
  for (const { row, result } of results)
    if (result) Object.assign(out, { [row.factKey]: result.call }, result.facts);
  return out;
}

/**
 * Parse, store the catalog variants, and write one profile fact per row that
 * called. `source` is `genome`, so a later answer from the user overwrites it
 * the way any other fact would.
 */
export async function saveGenome(
  userId: string,
  uploadId: string,
  text: string,
): Promise<{ variants: number; facts: number; results: GenomeResult[] }> {
  const variants = parseGenome(text);
  const db = getDb();

  for (const v of variants)
    await db
      .insert(genomeVariants)
      .values({
        userId,
        uploadId,
        rsid: v.rsid,
        genotype: v.genotype,
        chromosome: v.chromosome,
        position: v.position,
      })
      .onConflictDoUpdate({
        target: [genomeVariants.userId, genomeVariants.rsid],
        set: {
          genotype: v.genotype,
          chromosome: v.chromosome,
          position: v.position,
          uploadId,
        },
      });

  const results = callGenome(variants);
  const facts = genomeFacts(results);
  for (const [key, value] of Object.entries(facts))
    await writeFact(userId, key, value, { source: "genome" });

  return {
    variants: variants.length,
    facts: Object.keys(facts).length,
    results,
  };
}

/** The stored variants for one user, back as the table the upload page prints. */
export async function loadGenome(userId: string): Promise<GenomeResult[]> {
  const rows = await getDb()
    .select()
    .from(genomeVariants)
    .where(eq(genomeVariants.userId, userId));
  return callGenome(
    rows.map((r) => ({
      rsid: r.rsid,
      genotype: r.genotype,
      chromosome: r.chromosome,
      position: r.position,
    })),
  );
}
