/**
 * A consumer genome raw file into the twelve rows of `GENOME_CATALOG`, and
 * nothing else.
 *
 * 23andMe writes `rsid chromosome position genotype`, AncestryDNA writes
 * `rsid chromosome position allele1 allele2`, both tab separated, both with
 * `#` comment blocks and a header line. The file has ~600k rows and we want
 * twenty of them, so the parser walks the text one line at a time and keeps
 * only what the catalog asks for. Nothing outside the catalog is ever stored
 * or shown.
 *
 * `parseGenome`, `callGenome` and `genomeFacts` are pure; `saveGenome` is the
 * one function that writes.
 */
import { eq } from "drizzle-orm";
import { getDb, genomeVariants } from "@/db";
import { writeFact } from "./facts";
import {
  bestGrade,
  CATALOG_RSIDS,
  geneMoves,
  GENOME_CATALOG,
  normalizeGenotype,
  type GeneMove,
  type GenomeCall,
  type GenomeRow,
} from "./genome-catalog";
import type { Grade } from "./hypotheses";

export interface ParsedVariant {
  rsid: string;
  chromosome: string | null;
  position: number | null;
  genotype: string;
}

/**
 * The first lines of a `.txt` upload, as the spec's sniff test wants them:
 * a 23andMe comment block, a bare 23andMe header, or the AncestryDNA header.
 */
export function looksLikeGenome(head: string): boolean {
  const text = head.slice(0, 4000);
  if (/^#\s*rsid/m.test(text)) return true;
  if (/^rsid\s+chromosome\s+position\s+genotype/im.test(text)) return true;
  if (/^rsid\s+chromosome\s+position\s+allele1\s+allele2/im.test(text))
    return true;
  return /^#\s*(This data file generated by (23andMe|AncestryDNA))/im.test(
    text,
  );
}

/** The catalog rsids this file carries. Everything else is dropped as it is read. */
export function parseGenome(text: string): ParsedVariant[] {
  const out: ParsedVariant[] = [];
  let at = 0;
  while (at < text.length) {
    let end = text.indexOf("\n", at);
    if (end === -1) end = text.length;
    const line = text.slice(at, end).trim();
    at = end + 1;
    if (!line || line.startsWith("#")) continue;
    // ponytail: a lookup before a split. 600k rows, twenty of them matter.
    if (!line.startsWith("rs")) continue;
    const cols = line.split(/\t| +/);
    const rsid = cols[0]!.toLowerCase();
    if (!CATALOG_RSIDS.has(rsid)) continue;
    const raw = cols.length >= 5 ? `${cols[3]}${cols[4]}` : (cols[3] ?? "");
    const genotype = normalizeGenotype(raw);
    if (!genotype) continue;
    const position = Number(cols[2]);
    out.push({
      rsid,
      chromosome: cols[1] ?? null,
      position: Number.isFinite(position) ? position : null,
      genotype,
    });
  }
  return out;
}

export interface GenomeResult {
  row: GenomeRow;
  /** null when this array does not carry the rsids the row needs. */
  result: GenomeCall | null;
  /** The rsids the row wanted and the file did not have. */
  absent: string[];
}

/** Every catalog row against one person's variants, in catalog order. */
export function callGenome(variants: ParsedVariant[]): GenomeResult[] {
  const byRsid: Record<string, string> = {};
  for (const v of variants) byRsid[v.rsid] = v.genotype;
  return GENOME_CATALOG.map((row) => ({
    row,
    result: row.call(byRsid),
    absent: row.rsids.filter((r) => !byRsid[r]),
  }));
}

/** The profile facts a set of calls writes: `{ "genome:apoe": "e3/e4", ... }`. */
export function genomeFacts(results: GenomeResult[]): Record<string, string> {
  const out: Record<string, string> = {};
  for (const { row, result } of results)
    if (result) Object.assign(out, { [row.factKey]: result.call }, result.facts);
  return out;
}

/**
 * Parse, store the catalog variants, and write one profile fact per row that
 * called. `source` is `genome`, so a later answer from the user overwrites it
 * the way any other fact would.
 */
export async function saveGenome(
  userId: string,
  uploadId: string,
  text: string,
): Promise<{ variants: number; facts: number; results: GenomeResult[] }> {
  const variants = parseGenome(text);
  const db = getDb();

  for (const v of variants)
    await db
      .insert(genomeVariants)
      .values({
        userId,
        uploadId,
        rsid: v.rsid,
        genotype: v.genotype,
        chromosome: v.chromosome,
        position: v.position,
      })
      .onConflictDoUpdate({
        target: [genomeVariants.userId, genomeVariants.rsid],
        set: {
          genotype: v.genotype,
          chromosome: v.chromosome,
          position: v.position,
          uploadId,
        },
      });

  const results = callGenome(variants);
  const facts = genomeFacts(results);
  for (const [key, value] of Object.entries(facts))
    await writeFact(userId, key, value, { source: "genome" });

  return {
    variants: variants.length,
    facts: Object.keys(facts).length,
    results,
  };
}

/** The stored variants for one user, back as the table the upload page prints. */
export async function loadGenome(userId: string): Promise<GenomeResult[]> {
  const rows = await getDb()
    .select()
    .from(genomeVariants)
    .where(eq(genomeVariants.userId, userId));
  return callGenome(
    rows.map((r) => ({
      rsid: r.rsid,
      genotype: r.genotype,
      chromosome: r.chromosome,
      position: r.position,
    })),
  );
}

/* ── one answer per condition ──────────────────────────────────────────── *
 *
 * Phase 32a item 3, `docs/mockups/v4/genome.html` sections 01 and 02. The page
 * answers first: one card per condition the genome actually speaks to. That
 * needs the matched rule, not a boolean, so `geneMoves` in `lib/genome-catalog.ts`
 * keeps it and this merges the result across genes.
 *
 * Pure: no database, no clock. It reads the catalogue and the calls and
 * nothing else.
 */

/** One condition, and what this person's genome did to it. */
export interface ConditionVerdict {
  conditionId: string;
  name: string;
  direction: "up" | "down" | "none";
  /** the multiplier or likelihood ratio the matched rule carries, or null */
  factor: number | null;
  grade: Grade;
  /** one plain sentence: why this answer, in the catalogue's own words */
  reason: string;
  testNeeded: boolean;
  /** true when the answer comes from an ABSENCE rather than a call */
  absent: boolean;
  /** the catalogue rows that produced it */
  geneIds: string[];
}

/**
 * Every condition the person's calls touch, in catalogue-row order.
 *
 * Merge rule, when several genes point at one condition: the direction is up
 * if any gene pushed it up, else down if any pushed it down, else none; the
 * factor is the product of the factors that agree with that direction, so two
 * ×1.2 nudges compose to ×1.44 rather than fighting; the grade is the best of
 * them (A beats B); the reason names every gene that agreed; `testNeeded` is
 * true when any of them says so; and `absent` holds only when every down move
 * came from an absence. A row the array could not call says nothing at all,
 * so it produces no verdict.
 */
export function genomeVerdicts(
  rows: GenomeRow[],
  calls: GenomeResult[],
): ConditionVerdict[] {
  const byCondition = new Map<string, { v: ConditionVerdict; moves: GeneMove[] }>();
  const order: string[] = [];

  for (const row of rows) {
    const result = calls.find((c) => c.row.id === row.id)?.result;
    if (!result) continue;
    for (const move of geneMoves(row, result)) {
      const seen = byCondition.get(move.conditionId);
      if (!seen) {
        order.push(move.conditionId);
        byCondition.set(move.conditionId, {
          v: { ...move, geneIds: [row.id] },
          moves: [move],
        });
        continue;
      }
      seen.moves.push(move);
      seen.v.geneIds.push(row.id);
    }
  }

  return order.map((id) => {
    const { v, moves } = byCondition.get(id)!;
    const direction = moves.some((m) => m.direction === "up")
      ? "up"
      : moves.some((m) => m.direction === "down")
        ? "down"
        : "none";
    const agree = moves.filter((m) => m.direction === direction);
    const factors = agree
      .map((m) => m.factor)
      .filter((f): f is number => f != null);
    return {
      ...v,
      direction,
      factor: factors.length ? factors.reduce((a, b) => a * b, 1) : null,
      grade: bestGrade(
        agree.map((m) => m.grade),
        v.grade,
      ),
      reason: agree.map((m) => m.reason).join(" "),
      testNeeded: agree.some((m) => m.testNeeded),
      absent: direction === "down" && agree.every((m) => m.absent),
    };
  });
}

/** The catalogue rows that moved something, as the gene table asks it. */
export const movedIds = (verdicts: ConditionVerdict[]): Set<string> =>
  new Set(
    verdicts.filter((v) => v.direction !== "none").flatMap((v) => v.geneIds),
  );

/** `1.4`, `1.96`, `0.1`: a factor without the floating-point tail. */
export const factorText = (f: number): string => String(Number(f.toFixed(2)));

/**
 * What one verdict did, in the words the table's "What it moved" column uses:
 * "Type 2 diabetes ×1.4", "Coeliac disease · LR 0.1 against", or the condition
 * named as unchanged. Nothing here is invented; the number is the catalogue's.
 */
export function movedLine(v: ConditionVerdict): string {
  if (v.direction === "up" && v.factor != null)
    return `${v.name} ×${factorText(v.factor)}`;
  if (v.direction === "down" && v.factor != null)
    return `${v.name} · LR ${factorText(v.factor)} against`;
  return `${v.name} unchanged`;
}
