#!/usr/bin/env python3
"""Generate apps/ios/OpenVitals/Fixtures.swift from apps/ios/Tests/Fixtures/*.json.

The JSON files are the canonical contract fixtures; they are copied out of
`apps/simple/fixtures/api/`, which is where the web writes them. The Swift
file is the same bytes compiled in, so a DEBUG build can draw every screen
with no server behind it.

    python3 apps/ios/scripts/gen-fixtures.py

`ContractTests.testTheCompiledFixturesMatchTheFiles` fails the moment the two
sides drift, so a hand edit on either side is caught.
"""

from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
FIXTURES = ROOT / "Tests" / "Fixtures"
OUT = ROOT / "OpenVitals" / "Fixtures.swift"

HEAD = '''import Foundation

/// The contract's fixtures, compiled in so a DEBUG build can draw every
/// screen with no server behind it.
///
/// Generated by `apps/ios/scripts/gen-fixtures.py` from
/// `apps/ios/Tests/Fixtures/*.json`, which are the canonical files, copied
/// from `apps/simple/fixtures/api/`.
/// `ContractTests.testTheCompiledFixturesMatchTheFiles` fails the moment the
/// two drift apart.
enum Fixtures {

    /// On when the app is launched with `-OVFixtures YES`, which is how the
    /// screenshots are taken. Never on in a release build.
    static var on: Bool {
        #if DEBUG
        return UserDefaults.standard.bool(forKey: "OVFixtures")
        #else
        return false
        #endif
    }

    /// Which sheet a screenshot run should open on launch: `-OVSheet capture`
    /// or `-OVSheet settings`. Only read when the fixtures are on.
    static var sheet: String? {
        on ? UserDefaults.standard.string(forKey: "OVSheet") : nil
    }

    /// `-OVScheme dark` pins the appearance for a screenshot run, with or
    /// without the fixtures: the dark screens have to be photographed against
    /// the real server too. DEBUG only, so a shipped build always follows the
    /// phone.
    static var scheme: String? {
        #if DEBUG
        return UserDefaults.standard.string(forKey: "OVScheme")
        #else
        return nil
        #endif
    }

    /// `-OVGallery YES` opens the design-system gallery instead of the app.
    static var gallery: Bool {
        #if DEBUG
        return UserDefaults.standard.bool(forKey: "OVGallery")
        #else
        return false
        #endif
    }

    /// `-OVScreen marker` / `research` / `capture` opens one screen on launch
    /// against the real server, so a screenshot run reaches a sheet with no
    /// tap. DEBUG only, and unlike `-OVSheet` it does not turn the fixtures
    /// on: the point is a picture of the person's own data.
    static var screen: String? {
        #if DEBUG
        return UserDefaults.standard.string(forKey: "OVScreen")
        #else
        return nil
        #endif
    }

    /// `-OVBottom YES` opens every screen at the foot of its scroll, so a
    /// screenshot can prove the last row clears the tab bar.
    static var atBottom: Bool {
        on && UserDefaults.standard.bool(forKey: "OVBottom")
    }

    /// The canned answer for one endpoint, or nil when the app should ask the
    /// server like it always does.
    static func canned<T: Decodable>(_ name: String) -> T? {
        #if DEBUG
        guard on, let text = json[name] else { return nil }
        return try? JSONDecoder().decode(T.self, from: Data(text.utf8))
        #else
        return nil
        #endif
    }

    /// The JSON a release build must never carry.
    #if DEBUG
    static let json: [String: String] = [
'''

TAIL = """    ]
    #endif
}
"""


def main() -> int:
    names = sorted(p.stem for p in FIXTURES.glob("*.json"))
    if not names:
        print(f"no fixtures in {FIXTURES}", file=sys.stderr)
        return 1
    parts = [HEAD]
    for name in names:
        text = json.dumps(
            json.loads((FIXTURES / f"{name}.json").read_text()),
            indent=2, ensure_ascii=False)
        if '"""#' in text:
            print(f"{name}: closes the raw string", file=sys.stderr)
            return 1
        parts.append(f'        "{name}": #"""\n{text}\n"""#,\n')
    parts.append(TAIL)
    OUT.write_text("".join(parts))
    print(f"{OUT.relative_to(ROOT.parents[1])}: {len(names)} fixtures, "
          f"{OUT.stat().st_size // 1024} kB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
