#!/usr/bin/env python3
"""Generate apps/ios/OpenVitals/DesignTokens.swift from the design system CSS.

The design system is `docs/mockups/v4/system.css`. Its `:root` block is the
light column and its `.dark, html[data-theme="dark"]` block is the dark
column. This script reads both, and writes one Swift file that carries:

  * `light` and `dark`, the raw CSS values keyed by custom-property name.
    These are the contract the unit test re-parses.
  * typed constants: every colour as a light/dark `Color` pair, every
    spacing step, radius and type size as a `CGFloat`, every motion
    duration as a `TimeInterval`.

Run it after any edit to system.css:

    python3 apps/ios/scripts/gen-design.py

`apps/ios/Tests/DesignTokensTests.swift` parses the CSS again and fails when
the two sides disagree, so a hand edit on either side is caught.
"""

from __future__ import annotations

import hashlib
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[3]
CSS = ROOT / "docs" / "mockups" / "v4" / "system.css"
OUT = ROOT / "apps" / "ios" / "OpenVitals" / "DesignTokens.swift"
COPY = ROOT / "apps" / "ios" / "Tests" / "References" / "system.css"


def strip_comments(text: str) -> str:
    return re.sub(r"/\*.*?\*/", "", text, flags=re.S)


def block(css: str, selector: str) -> str:
    """The body of the first rule whose selector list matches `selector`."""
    for m in re.finditer(r"([^{}]+)\{([^{}]*)\}", css):
        sel = " ".join(m.group(1).split(";")[-1].split())
        if sel == selector:
            return m.group(2)
    raise SystemExit(f"no rule for {selector!r} in {CSS}")


def declarations(body: str) -> dict[str, str]:
    out: dict[str, str] = {}
    for line in body.split(";"):
        if ":" not in line:
            continue
        name, _, value = line.partition(":")
        name = name.strip()
        if not name.startswith("--"):
            continue
        out[name] = " ".join(value.split())
    return out


# ── value parsing ────────────────────────────────────────────────────────

HEX = re.compile(r"^#([0-9a-fA-F]{6})$")
RGBA = re.compile(r"^rgba?\(([^)]*)\)$")
PX = re.compile(r"^(-?[0-9.]+)px$")
MS = re.compile(r"^(-?[0-9.]+)ms$")


def colour(value: str) -> tuple[int, float] | None:
    """(0xrrggbb, alpha) for a hex or rgba() value, else None."""
    m = HEX.match(value)
    if m:
        return int(m.group(1), 16), 1.0
    m = RGBA.match(value)
    if m:
        parts = [p.strip() for p in m.group(1).replace("/", ",").split(",")]
        if len(parts) not in (3, 4):
            return None
        try:
            r, g, b = (int(float(p)) for p in parts[:3])
        except ValueError:
            return None
        a = float(parts[3]) if len(parts) == 4 else 1.0
        return (r << 16) | (g << 8) | b, a
    return None


def px(value: str) -> float | None:
    m = PX.match(value)
    return float(m.group(1)) if m else None


def ms(value: str) -> float | None:
    m = MS.match(value)
    return float(m.group(1)) if m else None


def swift_name(token: str) -> str:
    parts = token.lstrip("-").split("-")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def literal(n: float) -> str:
    return f"{n:g}"


def dictionary(name: str, values: dict[str, str]) -> str:
    def quote(s: str) -> str:
        return s.replace("\\", "\\\\").replace('"', '\\"')

    rows = "".join(
        f'        "{quote(k)}": "{quote(v)}",\n'
        for k, v in sorted(values.items())
    )
    return f"    static let {name}: [String: String] = [\n{rows}    ]\n"


def main() -> int:
    raw = CSS.read_text()
    css = strip_comments(raw)
    light = declarations(block(css, ":root"))
    dark = declarations(block(css, '.dark, html[data-theme="dark"]'))

    colours = [t for t in light if colour(light[t]) is not None]
    spaces = [t for t in light if px(light[t]) is not None]
    durations = [t for t in light if ms(light[t]) is not None]

    lines: list[str] = []
    w = lines.append
    w("// Generated by apps/ios/scripts/gen-design.py. Do not edit by hand.")
    w("//")
    w("// Source: docs/mockups/v4/system.css — the `:root` block is the light")
    w('// column, `.dark, html[data-theme="dark"]` is the dark one. Re-run the')
    w("// generator after any edit to that file; DesignTokensTests parses the")
    w("// CSS again and fails when the two sides disagree.")
    w("")
    w("import SwiftUI")
    w("import UIKit")
    w("")
    w("enum DesignTokens {")
    w("")
    w("    /// sha256 of the system.css this file was generated from.")
    w(f'    static let cssSHA256 = "{hashlib.sha256(raw.encode()).hexdigest()}"')
    w("")
    w("    // ── the raw CSS values, the contract the test re-parses ──────────")
    w("")
    w(dictionary("light", light).rstrip("\n"))
    w("")
    w(dictionary("dark", dark).rstrip("\n"))
    w("")
    w("    // ── colours: a light value and its dark twin ─────────────────────")
    w("")
    w("    struct Ink: Equatable {")
    w("        let rgb: UInt32")
    w("        let alpha: Double")
    w("    }")
    w("")
    w("    struct Pair: Equatable {")
    w("        let light: Ink")
    w("        let dark: Ink")
    w("")
    w("        var uiColor: UIColor {")
    w("            UIColor { traits in")
    w("                let side = traits.userInterfaceStyle == .dark")
    w("                    ? self.dark : self.light")
    w("                return UIColor(rgb: side.rgb, alpha: side.alpha)")
    w("            }")
    w("        }")
    w("")
    w("        var color: Color { Color(uiColor) }")
    w("    }")
    w("")
    for token in sorted(colours):
        lrgb, la = colour(light[token])
        drgb, da = colour(dark.get(token, light[token]))
        name = swift_name(token)
        w(f"    static let {name} = Pair(")
        w(f"        light: Ink(rgb: 0x{lrgb:06x}, alpha: {la:g}),")
        w(f"        dark: Ink(rgb: 0x{drgb:06x}, alpha: {da:g}))")
    w("")
    w("    /// Every colour token, by its CSS name.")
    w("    static let colours: [String: Pair] = [")
    for token in sorted(colours):
        w(f'        "{token}": {swift_name(token)},')
    w("    ]")
    w("")
    w("    // ── space, radii, type: every px token ───────────────────────────")
    w("")
    for token in sorted(spaces):
        w(f"    static let {swift_name(token)}: CGFloat = {literal(px(light[token]))}")
    w("")
    w("    static let lengths: [String: CGFloat] = [")
    for token in sorted(spaces):
        w(f'        "{token}": {swift_name(token)},')
    w("    ]")
    w("")
    w("    // ── motion: every ms token, in seconds ───────────────────────────")
    w("")
    for token in sorted(durations):
        secs = ms(light[token]) / 1000
        w(f"    static let {swift_name(token)}: TimeInterval = {secs:g}")
    w("")
    w("    static let durations: [String: TimeInterval] = [")
    for token in sorted(durations):
        w(f'        "{token}": {swift_name(token)},')
    w("    ]")
    w("")
    w("    /// The design's own easing curve, `--ease` and its twins.")
    w("    static let ease = UnitCurve.bezier(")
    w("        startControlPoint: UnitPoint(x: 0.22, y: 1),")
    w("        endControlPoint: UnitPoint(x: 0.36, y: 1))")
    w("}")
    w("")

    OUT.write_text("\n".join(lines))
    COPY.parent.mkdir(parents=True, exist_ok=True)
    COPY.write_text(raw)
    print(f"{OUT.relative_to(ROOT)}: {len(colours)} colours, "
          f"{len(spaces)} lengths, {len(durations)} durations")
    print(f"{COPY.relative_to(ROOT)}: {len(raw)} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
