// Generated by apps/ios/scripts/gen-design.py. Do not edit by hand.
//
// Source: docs/mockups/v4/system.css — the `:root` block is the light
// column, `.dark, html[data-theme="dark"]` is the dark one. Re-run the
// generator after any edit to that file; DesignTokensTests parses the
// CSS again and fails when the two sides disagree.

import SwiftUI
import UIKit

enum DesignTokens {

    /// sha256 of the system.css this file was generated from.
    static let cssSHA256 = "e630ca378723a408b145a6d24ea1e3337e86e42c9df588709ea3a383135ebdde"

    // ── the raw CSS values, the contract the test re-parses ──────────

    static let light: [String: String] = [
        "--bad": "#c32b45",
        "--bad-fill": "#e74d64",
        "--canvas": "#fdf5ec",
        "--canvas-deep": "#f4e9dc",
        "--digit-blur": "3px",
        "--digit-distance": "8px",
        "--digit-dur": "400ms",
        "--digit-ease": "cubic-bezier(0.22, 1, 0.36, 1)",
        "--digit-stagger": "40ms",
        "--dur-fast": "250ms",
        "--dur-quick": "150ms",
        "--ease": "cubic-bezier(0.22, 1, 0.36, 1)",
        "--flip-dur": "400ms",
        "--font-body": "var(--font-display)",
        "--font-display": "\"Geist\", \"Geist Sans\", \"Inter\", system-ui, -apple-system, \"Helvetica Neue\", Arial, sans-serif",
        "--font-mono": "\"Geist Mono\", \"JetBrains Mono\", ui-monospace, \"SF Mono\", SFMono-Regular, Menlo, monospace",
        "--hair": "rgba(61, 42, 28, 0.12)",
        "--icon-swap-dur": "200ms",
        "--ink": "#3d2a1c",
        "--ink-2": "#6d5744",
        "--ink-3": "#7f6a59",
        "--lime": "#d7f24b",
        "--lime-ink": "#1d2405",
        "--navy": "#0f2140",
        "--navy-bad": "#e3767c",
        "--navy-ink": "#f4f2ed",
        "--navy-ink-2": "rgba(244, 242, 237, 0.72)",
        "--navy-ok": "#8fc46a",
        "--navy-warn": "#e0a63c",
        "--none": "#7f6a59",
        "--ok": "#2b7f3a",
        "--r-card": "21px",
        "--r-hero": "34px",
        "--r-inner": "13px",
        "--r-pill": "999px",
        "--reveal-dur": "400ms",
        "--s13": "13px",
        "--s21": "21px",
        "--s3": "3px",
        "--s34": "34px",
        "--s5": "5px",
        "--s55": "55px",
        "--s8": "8px",
        "--sky": "#d9e7f7",
        "--stagger-blur": "3px",
        "--stagger-distance": "12px",
        "--stagger-dur": "500ms",
        "--stagger-stagger": "40ms",
        "--surface": "rgba(255, 255, 255, 0.58)",
        "--surface-flat": "#fefbf7",
        "--surface-hi": "rgba(255, 255, 255, 0.78)",
        "--tabs-dur": "250ms",
        "--tabs-ease": "cubic-bezier(0.22, 1, 0.36, 1)",
        "--text-swap-dur": "250ms",
        "--text-swap-ease": "cubic-bezier(0.22, 1, 0.36, 1)",
        "--toast-dur": "300ms",
        "--track": "#ece0d1",
        "--type-lg": "21px",
        "--type-md": "15px",
        "--type-sm": "13px",
        "--type-xl": "34px",
        "--type-xs": "11px",
        "--warn": "#9a6413",
    ]

    static let dark: [String: String] = [
        "--bad": "#e3767c",
        "--bad-fill": "#e3767c",
        "--canvas": "#121110",
        "--canvas-deep": "#0c0b0a",
        "--hair": "rgba(241, 239, 234, 0.11)",
        "--ink": "#f1efea",
        "--ink-2": "#b4aea4",
        "--ink-3": "#979083",
        "--none": "#979083",
        "--ok": "#8fc46a",
        "--sky": "#1b2b44",
        "--surface": "#1c1a18",
        "--surface-flat": "#1c1a18",
        "--surface-hi": "#24221f",
        "--track": "#2c2a26",
        "--warn": "#e0a63c",
    ]

    // ── colours: a light value and its dark twin ─────────────────────

    struct Ink: Equatable {
        let rgb: UInt32
        let alpha: Double
    }

    struct Pair: Equatable {
        let light: Ink
        let dark: Ink

        var uiColor: UIColor {
            UIColor { traits in
                let side = traits.userInterfaceStyle == .dark
                    ? self.dark : self.light
                return UIColor(rgb: side.rgb, alpha: side.alpha)
            }
        }

        var color: Color { Color(uiColor) }
    }

    static let bad = Pair(
        light: Ink(rgb: 0xc32b45, alpha: 1),
        dark: Ink(rgb: 0xe3767c, alpha: 1))
    static let badFill = Pair(
        light: Ink(rgb: 0xe74d64, alpha: 1),
        dark: Ink(rgb: 0xe3767c, alpha: 1))
    static let canvas = Pair(
        light: Ink(rgb: 0xfdf5ec, alpha: 1),
        dark: Ink(rgb: 0x121110, alpha: 1))
    static let canvasDeep = Pair(
        light: Ink(rgb: 0xf4e9dc, alpha: 1),
        dark: Ink(rgb: 0x0c0b0a, alpha: 1))
    static let hair = Pair(
        light: Ink(rgb: 0x3d2a1c, alpha: 0.12),
        dark: Ink(rgb: 0xf1efea, alpha: 0.11))
    static let ink = Pair(
        light: Ink(rgb: 0x3d2a1c, alpha: 1),
        dark: Ink(rgb: 0xf1efea, alpha: 1))
    static let ink2 = Pair(
        light: Ink(rgb: 0x6d5744, alpha: 1),
        dark: Ink(rgb: 0xb4aea4, alpha: 1))
    static let ink3 = Pair(
        light: Ink(rgb: 0x7f6a59, alpha: 1),
        dark: Ink(rgb: 0x979083, alpha: 1))
    static let lime = Pair(
        light: Ink(rgb: 0xd7f24b, alpha: 1),
        dark: Ink(rgb: 0xd7f24b, alpha: 1))
    static let limeInk = Pair(
        light: Ink(rgb: 0x1d2405, alpha: 1),
        dark: Ink(rgb: 0x1d2405, alpha: 1))
    static let navy = Pair(
        light: Ink(rgb: 0x0f2140, alpha: 1),
        dark: Ink(rgb: 0x0f2140, alpha: 1))
    static let navyBad = Pair(
        light: Ink(rgb: 0xe3767c, alpha: 1),
        dark: Ink(rgb: 0xe3767c, alpha: 1))
    static let navyInk = Pair(
        light: Ink(rgb: 0xf4f2ed, alpha: 1),
        dark: Ink(rgb: 0xf4f2ed, alpha: 1))
    static let navyInk2 = Pair(
        light: Ink(rgb: 0xf4f2ed, alpha: 0.72),
        dark: Ink(rgb: 0xf4f2ed, alpha: 0.72))
    static let navyOk = Pair(
        light: Ink(rgb: 0x8fc46a, alpha: 1),
        dark: Ink(rgb: 0x8fc46a, alpha: 1))
    static let navyWarn = Pair(
        light: Ink(rgb: 0xe0a63c, alpha: 1),
        dark: Ink(rgb: 0xe0a63c, alpha: 1))
    static let none = Pair(
        light: Ink(rgb: 0x7f6a59, alpha: 1),
        dark: Ink(rgb: 0x979083, alpha: 1))
    static let ok = Pair(
        light: Ink(rgb: 0x2b7f3a, alpha: 1),
        dark: Ink(rgb: 0x8fc46a, alpha: 1))
    static let sky = Pair(
        light: Ink(rgb: 0xd9e7f7, alpha: 1),
        dark: Ink(rgb: 0x1b2b44, alpha: 1))
    static let surface = Pair(
        light: Ink(rgb: 0xffffff, alpha: 0.58),
        dark: Ink(rgb: 0x1c1a18, alpha: 1))
    static let surfaceFlat = Pair(
        light: Ink(rgb: 0xfefbf7, alpha: 1),
        dark: Ink(rgb: 0x1c1a18, alpha: 1))
    static let surfaceHi = Pair(
        light: Ink(rgb: 0xffffff, alpha: 0.78),
        dark: Ink(rgb: 0x24221f, alpha: 1))
    static let track = Pair(
        light: Ink(rgb: 0xece0d1, alpha: 1),
        dark: Ink(rgb: 0x2c2a26, alpha: 1))
    static let warn = Pair(
        light: Ink(rgb: 0x9a6413, alpha: 1),
        dark: Ink(rgb: 0xe0a63c, alpha: 1))

    /// Every colour token, by its CSS name.
    static let colours: [String: Pair] = [
        "--bad": bad,
        "--bad-fill": badFill,
        "--canvas": canvas,
        "--canvas-deep": canvasDeep,
        "--hair": hair,
        "--ink": ink,
        "--ink-2": ink2,
        "--ink-3": ink3,
        "--lime": lime,
        "--lime-ink": limeInk,
        "--navy": navy,
        "--navy-bad": navyBad,
        "--navy-ink": navyInk,
        "--navy-ink-2": navyInk2,
        "--navy-ok": navyOk,
        "--navy-warn": navyWarn,
        "--none": none,
        "--ok": ok,
        "--sky": sky,
        "--surface": surface,
        "--surface-flat": surfaceFlat,
        "--surface-hi": surfaceHi,
        "--track": track,
        "--warn": warn,
    ]

    // ── space, radii, type: every px token ───────────────────────────

    static let digitBlur: CGFloat = 3
    static let digitDistance: CGFloat = 8
    static let rCard: CGFloat = 21
    static let rHero: CGFloat = 34
    static let rInner: CGFloat = 13
    static let rPill: CGFloat = 999
    static let s13: CGFloat = 13
    static let s21: CGFloat = 21
    static let s3: CGFloat = 3
    static let s34: CGFloat = 34
    static let s5: CGFloat = 5
    static let s55: CGFloat = 55
    static let s8: CGFloat = 8
    static let staggerBlur: CGFloat = 3
    static let staggerDistance: CGFloat = 12
    static let typeLg: CGFloat = 21
    static let typeMd: CGFloat = 15
    static let typeSm: CGFloat = 13
    static let typeXl: CGFloat = 34
    static let typeXs: CGFloat = 11

    static let lengths: [String: CGFloat] = [
        "--digit-blur": digitBlur,
        "--digit-distance": digitDistance,
        "--r-card": rCard,
        "--r-hero": rHero,
        "--r-inner": rInner,
        "--r-pill": rPill,
        "--s13": s13,
        "--s21": s21,
        "--s3": s3,
        "--s34": s34,
        "--s5": s5,
        "--s55": s55,
        "--s8": s8,
        "--stagger-blur": staggerBlur,
        "--stagger-distance": staggerDistance,
        "--type-lg": typeLg,
        "--type-md": typeMd,
        "--type-sm": typeSm,
        "--type-xl": typeXl,
        "--type-xs": typeXs,
    ]

    // ── motion: every ms token, in seconds ───────────────────────────

    static let digitDur: TimeInterval = 0.4
    static let digitStagger: TimeInterval = 0.04
    static let durFast: TimeInterval = 0.25
    static let durQuick: TimeInterval = 0.15
    static let flipDur: TimeInterval = 0.4
    static let iconSwapDur: TimeInterval = 0.2
    static let revealDur: TimeInterval = 0.4
    static let staggerDur: TimeInterval = 0.5
    static let staggerStagger: TimeInterval = 0.04
    static let tabsDur: TimeInterval = 0.25
    static let textSwapDur: TimeInterval = 0.25
    static let toastDur: TimeInterval = 0.3

    static let durations: [String: TimeInterval] = [
        "--digit-dur": digitDur,
        "--digit-stagger": digitStagger,
        "--dur-fast": durFast,
        "--dur-quick": durQuick,
        "--flip-dur": flipDur,
        "--icon-swap-dur": iconSwapDur,
        "--reveal-dur": revealDur,
        "--stagger-dur": staggerDur,
        "--stagger-stagger": staggerStagger,
        "--tabs-dur": tabsDur,
        "--text-swap-dur": textSwapDur,
        "--toast-dur": toastDur,
    ]

    /// The design's own easing curve, `--ease` and its twins.
    static let ease = UnitCurve.bezier(
        startControlPoint: UnitPoint(x: 0.22, y: 1),
        endControlPoint: UnitPoint(x: 0.36, y: 1))
}
